### ISSUE TITLE
Thanks for sharing

### ISSUE THREAD

**Issue by lbutler** [namur007/Infowater#1]
Thanks for sharing your collection of tools for InfoWater models!

My background is mostly with InfoWorks WS Pro which has a full set of APIs to let you code directly within the application and I've only recently started using InfoWater. I've been wanting to do some coding in InfoWater but I wasn't sure where to even start so this repo was a massive help.

One quick question, from what I've seen you're limited to working with the output files and the geographic layers within ArcGIS and don't have any way to directly interface with InfoWater, correct?

Keep up the good work, I'm hoping to share some tools for InfoWater as well to go with my InfoWorks WS Pro open source tools.

**Comment by cody-scott** [comment]
Happy to share!

Infowater unfortunately does not have an API to work with/manipulate models. It would be my number 1 feature for Innovyze add one to infowater pro. 

Consequently, this means all processing needs to be done on outputs such as the report files or data exported from the EXT_APP_FILTER option. 

There isn't many tools I've seen for infowater so I'm always interested to see what others are working on.

**Comment by lbutler** [comment]
I'm not sure if you're familiar with InfoWorks WS Pro but if you wanted to see examples of the API Innovyze set up I've got a repo here:
https://github.com/modelcreate/infoworks-ruby-scripts/

The other alternative I thought to using the EXT_APP_FILTER option would be to reading the HYDQUA.OUT binary file. I'm assuming its a modification of the EPANET structure so a little reverse engineering and you could access all the time series data.

I saw you're based out of Kitchener, I work for C3 Water in Breslau, maybe we will cross paths in the future. If you're ever interested in learning more about any of my open source work feel free to shot me an email, luke@matrado.ca or luke.butler@c3water.com.

It's a rare combination to be both a modeller and a programmer!
